### ISSUE TITLE
map list: show and sort by last-modfied date/time

### ISSUE THREAD

**Issue by caver456** [ncssar/sartopo-feature-requests#39]
Looks like this is already present in sartopo online; would be very handy for offline as well

**Comment by mtjacobs** [comment]
With the exception of a few items tied to Google Maps or my python/postgis stack, all online features will eventually work their way over, but for stability reasons the offline version is on a delay.  You can always grab the nightly sar.jar but I wouldn't recommend using it on the trailer for live searches.

**Comment by caver456** [comment]
this has been in place in STO for a few months; closing this old issue
